# Generated by Django 5.2.6 on 2025-11-04 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='review',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='shopcategory',
            name='shop',
        ),
        migrations.AlterUniqueTogether(
            name='shopcategory',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
        migrations.DeleteModel(
            name='ShopCategory',
        ),
    ]
